name: 'release-action'
description: 'Bumps package version and creates release.'

inputs:
  base-branch:
    description: 'Branch in which release will be merged'
    required: true
    default: 'main'

  head-branch:
    description: 'Branch to be released'
    required: true
    default: 'develop'

  github-token:
    description: 'GitHub token with access to commit in head-branch'
    required: true

  initial-version:
    description: "Initial version used if base-branch doesn't have package.json"
    default: '0.0.0'

  path:
    description: 'Path where the target package.json is located'
    default: ''

runs:
  using: 'node16'
  main: 'index.js'
