name: Pull request to main

on:
  pull_request:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: lemonenergy/release-action@develop
        id: release-commit
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/github-script@v6
        with:
          script: |
            if(!"${{steps.release-commit.outputs.version}}") return
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              title: "v${{steps.release-commit.outputs.version}}"
            })
